class: !!python/name:visual_dynamics.policies.quad_target_policy.QuadTargetPolicy ''
env: null
height_limits: [12, 12]
angle_limits: [2.356194490192345, 2.356194490192345]
radius_limits: [16, 16]
tightness: 1.0
