class: !!python/name:policy.mixed_policy.MixedPolicy ''
policies:
- class: !!python/name:policy.random_offset_camera_target_policy.RandomOffsetCameraTargetPolicy ''
  env: null
  target_env: null
  camera_node_name: quad_camera
  agent_node_name: quad
  target_node_name: car
  height: [10.5, 13.5]
  radius: [14.0, 18.0]
  angle: [-1.5707963267948966, 1.5707963267948966]
  tightness: 1.0
- class: !!python/name:policy.random_policy.RandomPolicy ''
  action_space: null
  state_space: null
act_probs: [0.25, 0.75]
reset_probs: [1, 0]
