class: !!python/name:visual_dynamics.policies.additive_normal_policy.AdditiveNormalPolicy ''
pol:
  class: !!python/name:visual_dynamics.policies.quad_target_policy.QuadTargetPolicy ''
  env: null
  height_limits: [12, 18]
  angle_limits: [-1.5707963267948966, 1.5707963267948966]
  tightness: 0.1
action_space: null
state_space: null
act_std: 0.2
