class: !!python/name:visual_dynamics.policies.momentum_policy.MomentumPolicy ''
policy:
  class: !!python/name:visual_dynamics.policies.random_policy.RandomPolicy ''
  action_space: null
  state_space: null
momentum: 0.9
