class: !!python/name:visual_dynamics.policies.mixed_policy.MixedPolicy ''
policies:
- class: !!python/name:visual_dynamics.policies.camera_target_policy.CameraTargetPolicy ''
  env: null
  target_env: null
  camera_node_name: quad_camera
  agent_node_name: quad
  target_node_name: car
  offset: [16.0, 0.0, 4.0]
  tightness: 1.0
- class: !!python/name:visual_dynamics.policies.random_policy.RandomPolicy ''
  action_space: null
  state_space: null
act_probs: [0.25, 0.75]
reset_probs: [1, 0]
