class: !!python/name:policy.momentum_policy.MomentumPolicy ''
policy:
  class: !!python/name:policy.mixed_policy.MixedPolicy ''
  policies:
  - class: !!python/name:policy.choice_policy.ChoicePolicy ''
    policies:
    - class: !!python/name:policy.camera_target_policy.CameraTargetPolicy ''
      env: null
      target_env: null
      camera_node_name: quad_camera
      agent_node_name: quad
      target_node_name: car
      offset: [-16.0, 0.0, 4.0]
      tightness: 1.0
    - class: !!python/name:policy.camera_target_policy.CameraTargetPolicy ''
      env: null
      target_env: null
      camera_node_name: quad_camera
      agent_node_name: quad
      target_node_name: car
      offset: [16.0, 0.0, 4.0]
      tightness: 1.0
    reset_probs: [0.5, 0.5]
  - class: !!python/name:policy.random_policy.RandomPolicy ''
    action_space: null
    state_space: null
  act_probs: [0.5, 0.5]
  reset_probs: [1, 0]
momentum: 0.9
