image:
  &id001
  class: !!python/name:utils.transformer.CompositionTransformer ''
  transformers:
  - &id002
    class: !!python/name:utils.transformer.ImageTransformer ''
    scale_size: 0.5
    crop_size: [128, 128]
    crop_offset: [0, 0]
  - class: !!python/name:utils.transformer.OpsTransformer ''
    transpose: !!python/tuple [2, 0, 1]

depth_image:
  &id003
  class: !!python/name:utils.transformer.CompositionTransformer ''
  transformers:
  - *id002
  - class: !!python/name:utils.transformer.DepthImageTransformer ''
    space: null

action:
  class: !!python/name:utils.transformer.NormalizerTransformer ''
  space: null
