class: !!python/name:envs.pr2_env.Pr2Env ''
action_space:
  class: !!python/name:spaces.box_space.BoxSpace ''
  high: [0.17453292519943295, 0.3490658503988659]
  low: [-0.17453292519943295, -0.3490658503988659]
  dtype: float64
observation_space:
  class: !!python/name:spaces.tuple_space.Tuple ''
  spaces:
  - class: !!python/name:spaces.box_space.BoxSpace ''
    low: 0
    high: 255
    shape: !!python/tuple [240, 320, 3]
    dtype: uint8
state_space:
  class: !!python/name:spaces.box_space.BoxSpace ''
  high: [0.5235987755982988, 0.6981317007977318]
  low: [-0.5235987755982988, 0.3490658503988659]
  dtype: float64
sensor_names: ['image']
