class: !!python/name:envs.quad_ogre_env.SimpleQuadOgreEnv ''
action_space:
  class: !!python/name:spaces.translation_axis_angle_space.TranslationAxisAngleSpace ''
  low: [-20, -10, -10, -1.5707963267948966]
  high: [20, 10, 10, 1.5707963267948966]
  axis: [0, 0, 1]
  dtype: float64
sensor_names: ['image']
car_env_class: !!python/name:envs.car_panda3d_env.GeometricCarPanda3dEnv ''
car_model_names: ['camaro2']
dt: 0.1
