class: !!python/name:visual_dynamics.envs.quad_panda3d_env.SimpleQuadPanda3dEnv ''
action_space:
  class: !!python/name:visual_dynamics.spaces.translation_axis_angle_space.TranslationAxisAngleSpace ''
  low: [-10, -10, -10, -1.5707963267948966]
  high: [10, 10, 10, 1.5707963267948966]
  axis: [0, 0, 1]
  dtype: float64
sensor_names: ['image']
camera_size: [256, 256]
camera_hfov: 26.007823885645635
car_env_class: !!python/name:visual_dynamics.envs.car_panda3d_env.GeometricCarPanda3dEnv ''
car_model_names: ['camaro2', 'mitsubishi_lancer_evo', 'sport', 'mercedes_s_class', 'dodge_viper_gts']
dt: 0.1
