class: !!python/name:predictor.solver.TheanoNetSolver ''
batch_size: 32
test_iter: 10
solver_type: ADAM
test_interval: 1000
base_lr: 0.001
gamma: 0.9
stepsize: 1000
display: 20
max_iter: 100000
momentum: 0.9
momentum2: 0.999
weight_decay: 0.0005
snapshot_interval: 1000
average_loss: 10
loss_interval: 200
plot_interval: 200

data_names: ['image', 'action']
data_name_offset_pairs: [['image', 0], ['action', 0], ['image', 1]]

train_data_fnames: ['data/simplequadgeomcarsides_train_data']
val_data_fname: 'data/simplequadgeomcarsides_val_data'
output_names: [[x0_next_pred, [x0, 1]], [x1_next_pred, [x1, 1]], [x2_next_pred, [x2, 1]]]
