class: !!python/name:predictor.solver.TheanoNetSolver ''
batch_size: 32
test_iter: 10
solver_type: ADAM
test_interval: 1000
base_lr: 0.001
gamma: 0.9
stepsize: 1000
display: 20
max_iter: 100000
momentum: 0.9
momentum2: 0.999
weight_decay: 0.0005
snapshot_interval: 5000
snapshot_prefix: 'gamma0.9_losslevels012345_simplequad_64'
average_loss: 10
loss_interval: 1000
plot_interval: 0

data_names: ['image', 'action']

train_data_fnames: ['data/simplequad_train_data']
val_data_fname: 'data/simplequad_val_data'
output_names: [[x5_next_pred, [x5, 1]]]
