class: !!python/name:predictor.solver.BilinearSolver ''
loss_batch_size: 32
aggregating_batch_size: 1000
test_iter: 10
weight_decay: 0.0005
average_loss: 10
data_names: ['image', 'action']
data_name_offset_pairs: [['image', 0], ['action', 0], ['image', 1]]

train_data_fnames: ['data/simplequadgeomcar_train_data']
val_data_fname: 'data/simplequadgeomcar_val_data'
output_names: [[x0_next_pred, [x0, 1]], [x1_next_pred, [x1, 1]], [x2_next_pred, [x2, 1]]]
