class: !!python/name:predictor.solver.BilinearSolver ''
loss_batch_size: 32
aggregating_batch_size: 1000
test_iter: 10
weight_decay: 0.0005
average_loss: 10
data_names: ['image', 'action']
data_name_offset_pairs: [['image', 0], ['action', 0], ['image', 1]]

train_data_fnames: ['data/simplequaddof4largexgeomcar_train_bigdata']
val_data_fname: 'data/simplequaddof4largexgeomcar_val_bigdata'
output_names: [[x5_0_next_pred, [x5_0, 1]], [x5_1_next_pred, [x5_1, 1]], [x5_2_next_pred, [x5_2, 1]]]
