class: !!python/name:predictor.solver.BilinearSolver ''
loss_batch_size: 32
aggregating_batch_size: 1000
test_iter: 10
weight_decay: 0.0005
snapshot_prefix: 'bilinear_losslevels0_simplequaddof4pitchsmall'
average_loss: 10
data_names: ['car_image', 'action']
#data_names: ['image', 'depth_image', 'car_image', 'car_depth_image', 'action']

train_data_fnames: ['data/simplequaddof4pitchsmall_train_data']
val_data_fname: 'data/simplequaddof4pitchsmall_val_data'
output_names: [[x0_next_pred, [x0, 1]]]
