class: !!python/name:predictor.solver.BilinearSolver ''
loss_batch_size: 32
aggregating_batch_size: 1000
test_iter: 10
weight_decay: 0.0005
snapshot_prefix: 'bilinear_losslevels012_citydof3'
average_loss: 10

train_data_fnames: ['data/citydof3_train_data']
val_data_fname: 'data/citydof3_val_data'
output_names: [[x0_next_pred, [x0, 1]]]
