class: !!python/name:predictor.solver.TheanoNetSolver ''
batch_size: 32
test_iter: 10
solver_type: SGD
test_interval: 1000
base_lr: 0.05
gamma: 0.9
stepsize: 1000
display: 20
max_iter: 10000
momentum: 0.9
momentum2: 0.999
weight_decay: 0.0005
snapshot_interval: 1000
snapshot_prefix: ''
average_loss: 10
loss_interval: 100
plot_interval: 0
