class: &id001 !!python/name:predictor.predictor_theano.TheanoNetHierarchicalFeaturePredictor ''
build_net: !!python/name:predictor.net_theano.build_dilated_vgg_action_cond_encoder_net ''
levels: [5]
bilinear_type: convolution
feature_name: [x5]
next_feature_name: [x5_next_pred]
feature_jacobian_name: [x5_diff_pred]
next_map_names: [x5_next_pred]
map_names: [x5]
pretrained_fname: models/theano/vgg/vgg_model.pkl
name: dilated_vgg_levels012345
