class: !!python/name:predictor.predictor_theano.TheanoNetHierarchicalFeaturePredictor ''
build_net: !!python/name:predictor.net_theano.build_multiscale_action_cond_encoder_net ''
levels: [0]
bilinear_type: share
feature_name: [x0]
next_feature_name: [x0_next_pred]
feature_jacobian_name: [x0_diff_pred]
map_names: [x0]
next_map_names: [x0_next_pred]
name: levels0
