class: !!python/name:predictor.predictor_theano.TheanoNetFeaturePredictor ''
build_net: !!python/name:predictor.net_theano.build_multiscale_action_cond_encoder_net ''
levels: [0, 1, 2]
bilinear_type: channelwise
feature_name: [x0, x1, x2]
next_feature_name: [x0_next_pred, x1_next_pred, x2_next_pred]
#feature_jacobian_name: [x0_diff_pred, x1_diff_pred, x2_diff_pred]
#map_names: [x0, x1, x2]
#next_map_names: [x0_next_pred, x1_next_pred, x2_next_pred]
name: multiscale_levels012
