class: !!python/name:predictor.predictor_theano.TheanoNetFeaturePredictor ''
build_net: !!python/name:predictor.net_theano.build_multiscale_action_cond_encoder_net ''
levels: [0, 1, 2]
bilinear_type: group_convolution
feature_name: [x0, x1, x2]
next_feature_name: [x0_next_pred, x1_next_pred, x2_next_pred]
name: multiscale_group_levels012
