class: !!python/name:predictor.predictor_theano.TheanoNetFeaturePredictor ''
build_net: !!python/name:predictor.net_theano.build_multiscale_dilated_vgg_action_cond_encoder_net ''
input_names: ['x', 'u']
num_encoding_levels: 2
scales: [0, 1, 2]
bilinear_type: channelwise_local
feature_name: [y2_0, y2_1, y2_2]
next_feature_name: [y2_0_next_pred, y2_1_next_pred, y2_2_next_pred]
control_name: 'u'
feature_jacobian_name: [y2_0_next_pred_jac, y2_1_next_pred_jac, y2_2_next_pred_jac]
pretrained_fname: models/theano/vgg16_model.h5
