class: !!python/name:predictor.predictor_theano.TheanoNetFeaturePredictor ''
build_net: !!python/name:predictor.net_theano.build_multiscale_dilated_vgg_action_cond_encoder_net ''
num_encoding_levels: 1
scales: [0, 1, 2]
bilinear_type: channelwise_local
tf_nl_layer: true
feature_name: [x1_0, x1_1, x1_2]
next_feature_name: [x1_0_next_pred, x1_1_next_pred, x1_2_next_pred]
pretrained_fname: models/theano/standarized_vgg/standarize_simplequad/_iter_1_model.pkl
