class: !!python/name:visual_dynamics.predictors.predictor_theano.TheanoNetFeaturePredictor ''
build_net: !!python/name:visual_dynamics.predictors.net_theano.build_multiscale_dilated_vgg_action_cond_encoder_net ''
input_names: ['x', 'u']
num_encoding_levels: 3
scales: [0, 1, 2]
bilinear_type: group_convolution
feature_name: [y3_0, y3_1, y3_2]
next_feature_name: [y3_0_next_pred, y3_1_next_pred, y3_2_next_pred]
control_name: 'u'
feature_jacobian_name: [y3_0_next_pred_jac, y3_1_next_pred_jac, y3_2_next_pred_jac]
pretrained_fname: models/theano/vgg16_model.h5
