class: !!python/name:predictor.predictor_theano.TheanoNetHierarchicalFeaturePredictor ''
build_net: !!python/name:predictor.net_theano.build_multiscale_action_cond_encoder_net ''
levels: [0, 1, 2]
bilinear_type: share
feature_name: [x0, x1, x2]
next_feature_name: [x0_next_pred, x1_next_pred, x2_next_pred]
feature_jacobian_name: [x0_diff_pred, x1_diff_pred, x2_diff_pred]
map_names: [x0, x1, x2]
next_map_names: [x0_next_pred, x1_next_pred, x2_next_pred]
name: multiscale_levels012

transformers:
- class: !!python/name:utils.transformer.CompositionTransformer ''
  transformers:
  - class: !!python/name:utils.transformer.ImageTransformer ''
    scale_size: 0.125
    crop_size: [32, 32]
    crop_offset: [0, 0]
  - class: !!python/name:utils.transformer.ScaleOffsetTransposeTransformer ''
    offset: null
    scale: null
    transpose: null
- class: !!python/name:utils.transformer.ScaleOffsetTransposeTransformer ''
  scale: null
  offset: null
  transpose: null
