class: !!python/name:predictor.predictor_theano.TheanoNetFeaturePredictor ''
build_net: !!python/name:predictor.net_theano.build_multiscale_dilated_vgg_action_cond_encoder_net ''
input_names: ['x', 'u']
num_encoding_levels: 0
scales: [0, 1, 2]
bilinear_type: group_convolution
feature_name: [y0_0, y0_1, y0_2]
next_feature_name: [y0_0_next_pred, y0_1_next_pred, y0_2_next_pred]
feature_jacobian_name: [y0_0_next_pred_jac, y0_1_next_pred_jac, y0_2_next_pred_jac]
