class: !!python/name:predictor.predictor_theano.TheanoNetFeaturePredictor ''
build_net: !!python/name:predictor.net_theano.build_multiscale_dilated_vgg_action_cond_encoder_net ''
input_names: ['x', 'u']
encoding_levels: [0, 1, 2, 3, 4, 5]
num_encoding_levels: 5
scales: [0, 1, 2]
bilinear_type: channelwise_local
feature_name: [y0_0, y0_1, y0_2, y1_0, y1_1, y1_2, y2_0, y2_1, y2_2, y3_0, y3_1, y3_2, y4_0, y4_1, y4_2, y5_0, y5_1, y5_2]
next_feature_name: [y0_0_next_pred, y0_1_next_pred, y0_2_next_pred, y1_0_next_pred, y1_1_next_pred, y1_2_next_pred, y2_0_next_pred, y2_1_next_pred, y2_2_next_pred, y3_0_next_pred, y3_1_next_pred, y3_2_next_pred, y4_0_next_pred, y4_1_next_pred, y4_2_next_pred, y5_0_next_pred, y5_1_next_pred, y5_2_next_pred]
control_name: 'u'
feature_jacobian_name: [y0_0_next_pred_jac, y0_1_next_pred_jac, y0_2_next_pred_jac, y1_0_next_pred_jac, y1_1_next_pred_jac, y1_2_next_pred_jac, y2_0_next_pred_jac, y2_1_next_pred_jac, y2_2_next_pred_jac, y3_0_next_pred_jac, y3_1_next_pred_jac, y3_2_next_pred_jac, y4_0_next_pred_jac, y4_1_next_pred_jac, y4_2_next_pred_jac, y5_0_next_pred_jac, y5_1_next_pred_jac, y5_2_next_pred_jac]
pretrained_fname: models/theano/vgg16_levelsall_model.h5
