class: !!python/name:predictor.predictor_theano.TheanoNetFeaturePredictor ''
build_net: !!python/name:predictor.net_theano.build_multiscale_dilated_vgg_action_cond_encoder_net ''
input_names: ['x', 'u']
encoding_levels: [0, 1, 2, 3, 4, 5]
num_encoding_levels: 5
scales: [0, 1, 2]
bilinear_type: channelwise_local
feature_name: [y0_0, y0_1, y0_2, y1_0, y1_1, y1_2, y2_0, y2_1, y2_2, y3_0, y3_1, y3_2, y4_0, y4_1, y4_2, y5_0, y5_1, y5_2]
next_feature_name: [y0_0_next_pred, y0_1_next_pred, y0_2_next_pred, y1_0_next_pred, y1_1_next_pred, y1_2_next_pred, y2_0_next_pred, y2_1_next_pred, y2_2_next_pred, y3_0_next_pred, y3_1_next_pred, y3_2_next_pred, y4_0_next_pred, y4_1_next_pred, y4_2_next_pred, y5_0_next_pred, y5_1_next_pred, y5_2_next_pred]
control_name: 'u'
feature_jacobian_name: [y0_0_next_pred_jac, y0_1_next_pred_jac, y0_2_next_pred_jac, y1_0_next_pred_jac, y1_1_next_pred_jac, y1_2_next_pred_jac, y2_0_next_pred_jac, y2_1_next_pred_jac, y2_2_next_pred_jac, y3_0_next_pred_jac, y3_1_next_pred_jac, y3_2_next_pred_jac, y4_0_next_pred_jac, y4_1_next_pred_jac, y4_2_next_pred_jac, y5_0_next_pred_jac, y5_1_next_pred_jac, y5_2_next_pred_jac]
pretrained_fname: models/theano/vgg16_levelsall_model.h5
environment_config:
  __class__: &id001 !!python/name:__builtin__.dict ''
  action_space:
    __class__: *id001
    axis: [0.0, 0.0, 1.0]
    class: &id002 !!python/name:spaces.translation_axis_angle_space.TranslationAxisAngleSpace ''
    dtype: float64
    high: [20.0, 10.0, 10.0, 1.5707963267948966]
    low: [-20.0, -10.0, -10.0, -1.5707963267948966]
  car_action_space:
    __class__: *id001
    class: &id003 !!python/name:spaces.box_space.BoxSpace ''
    dtype: float64
    high: [0.0, 0.0]
    low: [0.0, 0.0]
    shape: null
  car_env_class: &id004 !!python/name:envs.car_panda3d_env.GeometricCarPanda3dEnv ''
  car_model_name: [camaro2, mazda6, sport, kia_rio_blue, kia_rio_red, kia_rio_white]
  class: &id005 !!python/name:envs.quad_panda3d_env.SimpleQuadPanda3dEnv ''
  dt: 0.1
  offset: [0.0, -25.98076211353316, 15.0]
  sensor_names: [image]
transformers:
  action:
    class: &id008 !!python/name:utils.transformer.NormalizerTransformer ''
    space:
      axis: [0.0, 0.0, 1.0]
      class: *id002
      dtype: float64
      high: [20.0, 10.0, 10.0, 1.5707963267948966]
      low: [-20.0, -10.0, -10.0, -1.5707963267948966]
    transpose: null
  depth_image:
    class: &id006 !!python/name:utils.transformer.CompositionTransformer ''
    transformers:
    - class: &id007 !!python/name:utils.transformer.ImageTransformer ''
      crop_offset: [0, 0]
      crop_size: [128, 128]
      scale_size: 0.5
    - {class: !!python/name:utils.transformer.DepthImageTransformer '', space: null}
  image:
    class: *id006
    transformers:
    - class: *id007
      crop_offset: [0, 0]
      crop_size: [128, 128]
      scale_size: 0.5
    - class: &id009 !!python/name:utils.transformer.OpsTransformer ''
      exponent: 1.0
      offset: 0.0
      scale: 1.0
      transpose: !!python/tuple [2, 0, 1]
  u:
    class: *id008
    space:
      axis: [0.0, 0.0, 1.0]
      class: *id002
      dtype: float64
      high: [20.0, 10.0, 10.0, 1.5707963267948966]
      low: [-20.0, -10.0, -10.0, -1.5707963267948966]
    transpose: null
  x:
    class: *id006
    transformers:
    - class: *id007
      crop_offset: [0, 0]
      crop_size: [128, 128]
      scale_size: 0.5
    - class: *id009
      exponent: 1.0
      offset: 0.0
      scale: 1.0
      transpose: !!python/tuple [2, 0, 1]
