class: !!python/name:predictor.predictor_theano.TheanoNetHierarchicalFeaturePredictor ''
build_net: !!python/name:predictor.net_theano.build_vgg_fcn_action_cond_encoder_net ''
levels: [0, 1, 2, 3, 4, 5]
bilinear_type: share
feature_name: [x0, x1, x2, x3, x4, x5]
next_feature_name: [x0_next_pred, x1_next_pred, x2_next_pred, x3_next_pred, x4_next_pred, x5_next_pred]
feature_jacobian_name: [x0_diff_pred, x1_diff_pred, x2_diff_pred, x3_diff_pred, x4_diff_pred, x5_diff_pred]
next_map_names: [x0_next_pred, x1_next_pred, x2_next_pred, x3_next_pred, x4_next_pred, x5_next_pred]
map_names: [x0, x1, x2, x3, x4, x5]
pretrained_fname: models/theano/vgg/vgg_model.pkl
name: vgg_fcn_levels012345
#
#transformers:
#- class: !!python/name:utils.transformer.CompositionTransformer ''
#  transformers:
#  - class: !!python/name:utils.transformer.ImageTransformer ''
#    scale_size: 0.3
#    crop_size: [128, 128]
#    crop_offset: [0, 0]
#  - class: !!python/name:utils.transformer.ScaleOffsetTransposeTransformer ''
#    offset: [-0.81520784, -0.91591373, -0.97003922]
#    scale: 0.00784313725490196
#    transpose: null
#- class: !!python/name:utils.transformer.ScaleOffsetTransposeTransformer ''
#  scale: null
#  offset: null
#  transpose: null
